### ISSUE TITLE
I can't import phoenix lib 

### ISSUE THREAD

**Issue by villander** [dfreeman/ember-cli-node-assets#28]
I have in my `ember-cli-build`

```js
let app = new EmberApp(defaults, {
    'ember-cli-babel': {
      includePolyfill: true
    },
    nodeAssets: {
      // node asset options
      'phoenix': {
        srcDir: 'phoenix/assets/js',
        destDir: 'phoenix',
        vendor: {
          include: ['phoenix.js']
        }
      }
    },
```

Phoenix, in node modules 

![image](https://user-images.githubusercontent.com/10222774/32290528-7b75ed2a-bf21-11e7-807f-74e45bce2fe6.png)

But i have this erros

```
Error: ENOENT: no such file or directory, open '/Users/flama/Projects/vzon-web/tmp/source_map_concat-input_base_path-Z8Ot6uq0.tmp/vendor/phoenix/phoenix.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at SourceMap.addFile (/Users/flama/Projects/vzon-web/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /Users/flama/Projects/vzon-web/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (/Users/flama/Projects/vzon-web/node_modules/broccoli-concat/concat.js:198:24)
    at /Users/flama/Projects/vzon-web/node_modules/fast-sourcemap-concat/lib/source-map.js:419:12
    at initializePromise (/Users/flama/Projects/vzon-web/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/flama/Projects/vzon-web/node_modules/rsvp/dist/rsvp.js:1039:33)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/flama/Projects/vzon-web/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/flama/Projects/vzon-web/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Users/flama/Projects/vzon-web/node_modules/broccoli-merge-trees/index.js:36:53)
    at mergeTrees (/Users/flama/Projects/vzon-web/node_modules/ember-cli/lib/broccoli/merge-trees.js:46:18)
    at EmberApp.javascript (/Users/flama/Projects/vzon-web/node_modules/ember-cli/lib/broccoli/ember-app.js:1306:10)
    at EmberApp.toArray (/Users/flama/Projects/vzon-web/node_modules/ember-cli/lib/broccoli/ember-app.js:1674:10)
    at EmberApp.toTree (/Users/flama/Projects/vzon-web/node_modules/ember-cli/lib/broccoli/ember-app.js:1696:30)
    at module.exports (/Users/flama/Projects/vzon-web/ember-cli-build.js:71:14)
    at CoreObject.setupBroccoliBuilder (/Users/flama/Projects/vzon-web/node_modules/ember-cli/lib/models/builder.js:84:19)
    at CoreObject.init (/Users/flama/Projects/vzon-web/node_modules/ember-cli/lib/models/builder.js:64:10)
````

**Comment by dfreeman** [comment]
Hi @villander,

The `srcDir` is relative to the folder where the node package is, so the configuration you've got there will be looking for `phoenix/phoenix/assets/js/phoenix.js` — if you change to `srcDir: 'assets/js'`, I suspect things will work correctly.

That said, if you're on ember-cli >= 2.15, you don't even need this addon anymore and you can just write `app.import('node_modules/phoenix/assets/js/phoenix.js');` 🙂

**Comment by villander** [comment]
@dfreeman i changed to `srcDir: 'assets/js'` but i have this error. I'm using ember-cli 2.11

I need create a vendor? 

```js
Error: ENOENT: no such file or directory, open '/Users/flama/Projects/vzon-web/tmp/source_map_concat-input_base_path-QI3uixGv.tmp/vendor/phoenix/phoenix.js'
    at Error (native)
```

**Comment by dfreeman** [comment]
I just dropped this in a fresh `ember new`ed app and it seemed to work for me:

```js
module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    nodeAssets: {
      phoenix: {
        srcDir: 'assets/js',
        destDir: 'phoenix',
        vendor: {
          include: ['phoenix.js']
        }
      }
    }
  });

  app.import('vendor/phoenix/phoenix.js');

  return app.toTree();
};
```

**Comment by villander** [comment]
@dfreeman look my `ember-cli-build` it's not works for me

```js
/* jshint node:true*/
/* global require, module */
let EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    'ember-cli-babel': {
      includePolyfill: true
    },
    nodeAssets: {
      // node asset options
      'phoenix': {
        srcDir: 'assets/js',
        destDir: 'phoenix',
        vendor: {
          include: ['phoenix.js']
        }
      }
    }
  });

  app.import('vendor/phoenix/phoenix.js');

  // Use `app.import` to add additional libraries to the generated
  return app.toTree();
};
```

**Comment by dfreeman** [comment]
Is your project available in a public repo somewhere?

**Comment by villander** [comment]
@dfreeman now works, i did import like this. And all works

Thanks man!

```js
app.import('vendor/phoenix/phoenix.js', {
  using: [{ transformation: 'amd', as: 'phoenix' }]
});
```
